name: labels
on:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'
  repository_dispatch:
    types:
      - labels-update

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Run Labeler
        uses: jetersen/ghaction-github-labeler@fix/loadConfigGitHubApi
